version: '2'
services:
  elastickit:
    image: elasticsearch:7.10.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - ./data/data:/usr/share/elasticsearch/data
      - ./data/plugins:/usr/share/elasticsearch/plugins
  kibana:
    image: kibana:7.10.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS="http://elastickit:9200"
